apiVersion: v1
data:
  fieldPrefix: unique-\w+
  fieldSpecs:
  - path: metadata/name
  - path: metadata/namespace
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ../../dist/rnd-fn
  name: my-config
