apiVersion: v1
kind: Service
metadata:
  name: unique-svc
  namespace: unique-ns
spec:
  clusterIP: None
  ports:
  - name: etcd-server-ssl
    port: 2380
  - name: etcd-client-ssl
    port: 2379
  publishNotReadyAddresses: true
