apiVersion: v1
kind: ConfigMap
metadata:
  name: the-map
  namespace: unique-ns
data:
  some-key: some-value
---
apiVersion: v1
kind: Service
metadata:
  name: the-service
  namespace: unique-ns
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 2380
    name: etcd-server-ssl
  - port: 2379
    name: etcd-client-ssl